/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * loancalc.java
 *
 * Created on Feb 1, 2011, 12:22:49 AM
 */
//import JOptionPane
import javax.swing.JOptionPane;
//Import textfor currency format
import java.text.*;
/**
 *
 * @author Kris Andrews
 */
public class LoanCalc extends javax.swing.JFrame {

    /** Creates new form LoanCalc */
    public LoanCalc() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        priceField = new javax.swing.JTextField();
        downpayField = new javax.swing.JTextField();
        amtfinancedField = new javax.swing.JTextField();
        yrlyintrteField = new javax.swing.JTextField();
        yrsField = new javax.swing.JTextField();
        mthlypayField = new javax.swing.JTextField();
        intrpaidField = new javax.swing.JTextField();
        totalpayField = new javax.swing.JTextField();
        calcButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        priceLabel = new javax.swing.JLabel();
        downpayLabel = new javax.swing.JLabel();
        amtfinancedLabel = new javax.swing.JLabel();
        yrlyintrteLabel = new javax.swing.JLabel();
        yrsLabel = new javax.swing.JLabel();
        mthlypayLabel = new javax.swing.JLabel();
        totalpayLabel = new javax.swing.JLabel();
        intrpaidLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Car Loan");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 0, 255));
        setResizable(false);

        titleLabel.setFont(new java.awt.Font("Stencil", 0, 32));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Car Loan Calculator");
        titleLabel.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        priceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceFieldActionPerformed(evt);
            }
        });

        downpayField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downpayFieldActionPerformed(evt);
            }
        });

        amtfinancedField.setEditable(false);
        amtfinancedField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amtfinancedFieldActionPerformed(evt);
            }
        });

        mthlypayField.setEditable(false);

        intrpaidField.setEditable(false);
        intrpaidField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intrpaidFieldActionPerformed(evt);
            }
        });

        totalpayField.setEditable(false);

        calcButton.setBackground(new java.awt.Color(0, 0, 0));
        calcButton.setForeground(new java.awt.Color(255, 255, 255));
        calcButton.setText("Calculate");
        calcButton.setToolTipText("Click this button to calculate the loan");
        calcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonActionPerformed(evt);
            }
        });

        clearButton.setBackground(new java.awt.Color(0, 0, 0));
        clearButton.setForeground(new java.awt.Color(255, 255, 255));
        clearButton.setText("Clear");
        clearButton.setToolTipText("Click this button to clear all fields");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(0, 0, 0));
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("Exit");
        exitButton.setToolTipText("Click this button to exit the program");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        priceLabel.setText("Purchase Price");

        downpayLabel.setText("Down Payment");

        amtfinancedLabel.setText("Amount Financed");

        yrlyintrteLabel.setText("Yearly Interest Rate");

        yrsLabel.setText("Years");

        mthlypayLabel.setText("Monthly Payment");

        totalpayLabel.setText("Total of Payments");

        intrpaidLabel.setText("Total Interest Paid");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(priceLabel))
                            .addComponent(downpayLabel)
                            .addComponent(yrlyintrteLabel)
                            .addComponent(intrpaidLabel)
                            .addComponent(amtfinancedLabel)
                            .addComponent(yrsLabel)
                            .addComponent(mthlypayLabel)
                            .addComponent(totalpayLabel)
                            .addComponent(calcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(totalpayField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(intrpaidField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(mthlypayField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(yrsField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(yrlyintrteField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(amtfinancedField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(priceField, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(downpayField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                                .addGap(61, 61, 61))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))))
                    .addComponent(titleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel)
                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(downpayLabel)
                    .addComponent(downpayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amtfinancedLabel)
                    .addComponent(amtfinancedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(yrlyintrteLabel)
                    .addComponent(yrlyintrteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(yrsLabel)
                    .addComponent(yrsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mthlypayLabel)
                    .addComponent(mthlypayField, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intrpaidLabel)
                    .addComponent(intrpaidField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalpayLabel)
                    .addComponent(totalpayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void downpayFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downpayFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_downpayFieldActionPerformed

    private void amtfinancedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amtfinancedFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amtfinancedFieldActionPerformed

    private void calcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButtonActionPerformed
        // TODO add your handling code here:
       //Convert string to double and get text
        String pstr = priceField.getText();
        double p = Double.parseDouble(pstr);
        //show error message if condition is true
if(p <= 0)
{ JOptionPane.showMessageDialog(this,"Error, price must be greater than 0");
  return;
}
       //Convert string to double
        String dpstr = downpayField.getText();
        double dp = Double.parseDouble(dpstr);
        //show error message if condition is true
if(dp < 0 || p < dp )
{ JOptionPane.showMessageDialog(this,"Error, down payment must be greater than or equal to zero and less than or equal to the purchase price");
}
        // calculate amount financed
        double amtfinanced = p - dp;
        //define decimal format
        DecimalFormat currency = new DecimalFormat("$ #,##0.00");

        // display  amount financed
        amtfinancedField.setText(""+currency.format(amtfinanced));
        //Convert string to double and get text
        String yrstr = yrsField.getText();
        double yr = Double.parseDouble(yrstr);
         //show error message if condition is true
if(yr <= 0 || yr>10 )
{ JOptionPane.showMessageDialog(this,"years should be greater than 0 and less than or equal to 10.");
  return;
}
        //Convert string to double and get text
        String yintstr = yrlyintrteField.getText();
        double yint = Double.parseDouble(yintstr);
         //show error message if condition is true
if(yint < 0 || yint > 100 )
{ JOptionPane.showMessageDialog(this,"Error,yearly interest rate should be greater than or equal to zero and less than or equal to 100 ");
  return;
}
  //calculate monthly interest rate
 double mir = yint / 12 / 100;
  //calculate number of periods
 double np = 12 * yr;
 // calculate monthly payment
 double mpay = amtfinanced * mir /(1 - Math.pow((1+ mir),(-np)));
  //calculate total of payments
 double totop = np * mpay;
 // calculate total interest paid
 double  tintp = totop - amtfinanced;

 // display monthly payment
        mthlypayField.setText(""+currency.format(mpay));
 // display Total Interest Paid
        intrpaidField.setText(""+currency.format(tintp));
 // display  total of payments
        totalpayField.setText(""+currency.format(totop));


    }//GEN-LAST:event_calcButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        //clear all fields on Click
        priceField.setText("");
        downpayField.setText("");
        amtfinancedField.setText("");
        yrlyintrteField.setText("");
        yrsField.setText("");
        mthlypayField.setText("");
        intrpaidField.setText("");
        totalpayField.setText("");
 
    }//GEN-LAST:event_clearButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        //button to exit program
        System.exit(0);

    }//GEN-LAST:event_exitButtonActionPerformed

    private void priceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceFieldActionPerformed

private void intrpaidFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intrpaidFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_intrpaidFieldActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amtfinancedField;
    private javax.swing.JLabel amtfinancedLabel;
    private javax.swing.JButton calcButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField downpayField;
    private javax.swing.JLabel downpayLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField intrpaidField;
    private javax.swing.JLabel intrpaidLabel;
    private javax.swing.JTextField mthlypayField;
    private javax.swing.JLabel mthlypayLabel;
    private javax.swing.JTextField priceField;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField totalpayField;
    private javax.swing.JLabel totalpayLabel;
    private javax.swing.JTextField yrlyintrteField;
    private javax.swing.JLabel yrlyintrteLabel;
    private javax.swing.JTextField yrsField;
    private javax.swing.JLabel yrsLabel;
    // End of variables declaration//GEN-END:variables

}
